src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\Service\FileUploader;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=64)
     */
    private $name;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Please, upload an jpeg, jpg or png file.")
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\ProductLine", mappedBy="Product")
     */
    private $productLines;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Category", inversedBy="products")
     */
    private $Category;

    public function __construct()
    {
        $this->productLines = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    public function setImage( $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|ProductLine[]
     */
    public function getProductLines(): Collection
    {
        return $this->productLines;
    }

    public function addProductLine(ProductLine $productLine): self
    {
        if (!$this->productLines->contains($productLine)) {
            $this->productLines[] = $productLine;
            $productLine->setProduct($this);
        }

        return $this;
    }

    public function removeProductLine(ProductLine $productLine): self
    {
        if ($this->productLines->contains($productLine)) {
            $this->productLines->removeElement($productLine);
            // set the owning side to null (unless already changed)
            if ($productLine->getProduct() === $this) {
                $productLine->setProduct(null);
            }
        }

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->Category;
    }

    public function setCategory(?Category $Category): self
    {
        $this->Category = $Category;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use App\Entity\Category;

class ProductType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('description', TextareaType::class)
            ->add('price', MoneyType::class)
            ->add('image', FileType::class, array('data_class' => null))
            ->add('Category', EntityType::class, [
                "class" => Category::class,
                "choice_label" => "name"
            ]);
        
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
        ]);
    }
}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Product;
use App\Service\FileUploader;
use App\Repository\ProductRepository;
use App\Form\ProductType;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;


class ProductController extends AbstractController
{
    /**
     * @Route("/add/product", name="add_product")
     */
    public function index(Request $request, FileUploader $fileUploader)
    {

        $product = new Product();

        $form = $this->createForm(ProductType::class, $product);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            dump("bloho");
            /**
             * Pour mettre sur la bdd les informations d'un formulaire
             * on fait le formulaire comme d'hab, mais ici, on utilise
             * le manager et le persist/flush
             */
            $product = $form->getData();
            $file = $product->getImage();
            $fileName = $fileUploader->upload($file);
            $product->setImage($fileName);

            $em = $this->getDoctrine()->getManager();

            $em->persist($product);

            $em->flush();

            return $this->redirectToRoute('product', ["id" => $product->getId()]);
        }
        return $this->render('product/index.html.twig', [
            'form' => $form->createView()
        ]);
    }


    /**
     * @Route("/admin/product/{id}", name="product")
     */
    public function show(int $id, ProductRepository $repo, Request $request)
    {

        $product = $repo->find($id);


        return $this->render('product/show.html.twig', [

            "product" => $product

        ]);
    }

    /**
     * @Route("/admin/product/remove/{id}", name="remove_product")
     */
    public function remove(Product $product)
    {

        $em = $this->getDoctrine()->getManager();

        $em->remove($product);

        $em->flush();

        return $this->redirectToRoute("home", []);
    }


    /**
     * @Route("/admin/product/update/{id}", name="update_product")
     */

    public function update(Product $product, int $id, Request $request, FileUploader $fileUploader)
    {
        $product->setImage(new File("uploads/images/".$product->getImage()));
        dump($product);
        $form = $this->createForm( ProductType::class, $product);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $file = $product->getImage();
            $fileName = $fileUploader->upload($file);
            $product->setImage($fileName);
            $this->getDoctrine()->getManager()->flush();
            return $this->redirectToRoute('product', ["id" => $product->getId()]);
        }

        return $this->render('product/update.html.twig', array(
            'product' => $product,
            'form' => $form->createView(),
        ));

        return $this->redirectToRoute('product', ["id" => $product->getId()]);
    }
}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %} 
    <title>
        Add Product 
    </title>
{% endblock %}

{% block body %}

<div class="container" id="add-product">
    <h1>Add Product</h1>
{{form_start(form)}}
{{form_widget(form)}}
<button class="btn btn-primary">Add Product</button>
{{form_end(form)}}
</div>





{% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    <title>
        Product
    </title>
{% endblock %}

{% block body %}

<div class="container-fluid">
    <div class="col-md-5 mx-auto">
        <div class="card mb-3" id="product-page">
            <h3 class="card-header">{{product.name}}</h3>
            <img style="height: 710 px; width: 100%; display: block;" src="{{asset('uploads/images/'~product.image)}}" alt="Card image">
            <div class="list-group">
                    <a href="#" class="list-group-item list-group-item-action flex-column align-items-start active">
                      <div class="d-flex w-100 justify-content-between">
                        <h5 class="mb-1">List group item heading</h5>
                      </div>
                      <p class="mb-1"> {{product.description}} </p>
                    </a>
                  </div>
            <ul class="list-group list-group-flush">
            <li class="list-group-item">Catégorie: {{product.category.name}}</li>
            <li class="list-group-item">Price: {{product.price}} €</li>

            </ul>

            <div class="card-body">
                <form method="post" action="{{path('product_line', {id:product.id})}}">
                  <input type="number" name="number">
                  <button class="btn btn-primary">Add to cart</button>
                </form>
              </div>

            
            {# {% if is_granted('IS_AUTHENTICATED_REMEMBERED') %} #}
            <div class="card-footer text-muted">
                <a class="btn btn-primary" href="{{path('remove_product', {id:product.id})}}">Remove Product</a>
            </div>
            <div class="card-footer text-muted">
                <a class="btn btn-primary" href="{{path('update_product', {id:product.id})}}">Update Product</a>
            </div>
            {# {% endif %} #}
        </div>
    </div>
</div>

{% endblock %}

templates/product/update.html.twig
{% extends 'base.html.twig' %}

{% block title %} 
    <title>
        Update Product 
    </title>
{% endblock %}

{% block body %}

<div class="container" id="add-product">
    <h1>Update Product</h1>
{{form_start(form)}}
{{form_widget(form)}}
<button class="btn btn-primary">Update Product</button>
{{form_end(form)}}
</div>





{% endblock %}